### ISSUE TITLE
tensorflow problem

### ISSUE THREAD

**Issue by hftsai** [vanvalen/deepcell-tf#1]
Hi David,
I wonder if you could share a bit more information about your environment? the version of tensorflow and cudnn?

I'm getting
`ValueError:Negative dimension size caused by subtracting 3 from 1 form 'conv2d/Conv2D' (op: 'Conv2D) with input shapes:[?,1,61,61], [3, 3, 64,64]`
which from what i read the most common problem is image_dim_ordering not set correctly.

but i've already have my .keras.json as 
'
    "image_dim_ordering": "channels_first",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
'
so i wonder if i used a wrong version.

thank you so much.

**Comment by vanvalen** [comment]
I use CUDA 9 and cudnn 7. There should be a docker make file in the repo.

Dave

-------
David Van Valen MD, PhD
Visiting Associate, California Institute of Technology
Postdoctoral Scholar, Stanford University

**Comment by hftsai** [comment]
Thank you! I'll try a bit more
